# Generated by Django 3.1.4 on 2021-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_anniversary_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('ename', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('phnno', models.IntegerField()),
            ],
            options={
                'db_table': 'bookingdetails',
            },
        ),
    ]
