# Generated by Django 3.1.4 on 2021-05-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='anniversary',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthday',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
