# Generated by Django 3.1.4 on 2021-05-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_remove_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anniversary',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='rate',
        ),
    ]
